# 02-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-s3-backup
type: Opaque
stringData:
  root-password: password
  username: "<username>"
  password: "<password>"

---

apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: mysql-s3-backup
type: Opaque
stringData:
  AWS_ACCESS_KEY: "<AWS__ACCESS_KEY>"
  AWS_SECRET_ACCESS_KEY: "<AWS_SECRET_ACCESS_KEY>"
  AWS_DEFAULT_REGION: "<AWS_REGION>"
  S3_BUCKET_NAME: "<S3_BUCKET_NAME<"